port: 8700

favicon: "favicon.ico"
title: "PDT"
showservererror: true

database:
  server: "<your database server>"
  name: "<your database name>"
  username: "<your database username>"
  password: "<your database password>"

cookie: 
  persist: true
  secure: false
  lifetime: 24

template:
  cached: false
  dir: "data/template"  
  options:
  - missingkey=error

application:
  pagedir: "data/pages"
  contentdir: "data/content"

hittest: false

logging:
  enabled: true